diocesis/diocesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from principal.views import index

urlpatterns = [
	url(r'^$', index, name = 'index'),
    url(r'^admin/', admin.site.urls),
    url(r'^principal/', include('principal.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

diocesis/principal/urls.py
from django.conf.urls import url
from . import views

app_name = 'principal'

urlpatterns = [
	url(r'^$', views.index, name = 'index'),

	url(r'^empleado/$', views.empleado, name = 'empleado'),
	url(r'^empleado/guardar/$', views.empleado_guardar, name='empleado_guardar'),
	url(r'^empleado/desactivar/$', views.empleado_desactivar, name='empleado_desactivar'),
	url(r'^empleado/(?P<pk>\d+)/editar/$', views.empleado_editar, name='empleado_editar'),
	url(r'^empleado/editar_guardar/$', views.empleado_editar_guardar, name='empleado_editar_guardar'),

	url(r'^estudio/$', views.estudio, name = 'estudio'),
	url(r'^estudio/guardar/$', views.estudio_guardar, name='estudio_guardar'),
	url(r'^estudio/eliminar/$', views.estudio_eliminar, name='estudio_eliminar'),
	url(r'^estudio/(?P<pk>\d+)/editar/$', views.estudio_editar, name='estudio_editar'),
	url(r'^estudio/editar_guardar/$', views.estudio_editar_guardar, name='estudio_editar_guardar'),

	url(r'^obispo/$', views.obispo, name = 'obispo'),
	url(r'^obispo/(?P<pk>\d+)/ver/$', views.obispo_ver, name='obispo_ver'),
	url(r'^obispo/guardar/$', views.obispo_guardar, name='obispo_guardar'),
	url(r'^obispo/(?P<pk>\d+)/$', views.obispo_editar, name='obispo_editar'),
	url(r'^obispo/editar_guardar/$', views.obispo_editar_guardar, name='obispo_editar_guardar'),
	url(r'^obispo/(?P<pk>\d+)/desactivar/$', views.obispo_desactivar, name = 'obispo_desactivar'),

	url(r'^parroquia/$', views.parroquia, name = 'parroquia'),
	url(r'^parroquia/(?P<pk>\d+)/ver/$', views.parroquia_ver, name='parroquia_ver'),
	url(r'^parroquia/guardar/$', views.parroquia_guardar, name='parroquia_guardar'),
	url(r'^parroquia/(?P<pk>\d+)/$', views.parroquia_editar, name='parroquia_editar'),
	url(r'^parroquia/editar_guardar/(?P<pk>\d+)/$', views.parroquia_editar_guardar, name='parroquia_editar_guardar'),
	url(r'^parroquia/desactivar/(?P<pk>\d+)/$', views.parroquia_desactivar, name = 'parroquia_desactivar'),

	url(r'^parroquia_admin/$', views.parroquia_admin, name = 'parroquia_admin'),
	url(r'^parroquia_admin/guardar/$', views.parroquia_admin_guardar, name='parroquia_admin_guardar'),
	url(r'^parroquia_admin/desactivar/$', views.parroquia_admin_desactivar, name='parroquia_admin_desactivar'),
	url(r'^parroquia_admin/(?P<pk>\d+)/editar/$', views.parroquia_admin_editar, name='parroquia_admin_editar'),
	url(r'^parroquia_admin/editar_guardar/$', views.parroquia_admin_editar_guardar, name='parroquia_admin_editar_guardar'),

	url(r'^pastoral/$', views.pastoral, name = 'pastoral'),
	url(r'^pastoral/guardar/$', views.pastoral_guardar, name='pastoral_guardar'),
	url(r'^pastoral/(?P<pk>\d+)/$', views.pastoral_editar, name='pastoral_editar'),
	url(r'^pastoral/editar_guardar/$', views.pastoral_editar_guardar, name='pastoral_editar_guardar'),
	url(r'^pastoral/desactivar/$', views.pastoral_desactivar, name = 'pastoral_desactivar'),

	url(r'^sacerdote/$', views.sacerdote, name = 'sacerdote'),
	url(r'^sacerdote/(?P<pk>\d+)/ver/$', views.sacerdote_ver, name='sacerdote_ver'),
	url(r'^sacerdote/(?P<pk>\d+)/$', views.sacerdote_editar, name='sacerdote_editar'),
	url(r'^sacerdote/editar_guardar/(?P<pk>\d+)/$', views.sacerdote_editar_guardar, name='sacerdote_editar_guardar'),
	url(r'^sacerdote/desactivar/(?P<pk>\d+)/$', views.sacerdote_desactivar, name = 'sacerdote_desactivar'),


	url(r'^usuario/$', views.usuario, name = 'usuario'),
	url(r'^usuarios/guardar/$', views.usuarios_guardar, name='usuarios_guardar'),
	url(r'^usuarios/desactivar/$', views.usuarios_desactivar, name='usuarios_desactivar'),
	url(r'^usuarios/(?P<pk>\d+)/editar/$', views.usuarios_editar, name='usuarios_editar'),
	url(r'^usuarios/editar_guardar/$', views.usuario_editar_guardar, name='usuario_editar_guardar'),


	url(r'^homilia/$', views.homilia, name = 'homilia'),
	url(r'^nueva-homilia/$', views.nueva_homilia, name = 'nueva_homilia'),
	url(r'^detalle-homilia/(?P<id>\d+)/$', views.detalle_homilia, name = 'detalle_homilia'),
	url(r'^eliminar-homilia/(?P<id>\d+)/$', views.eliminar_homilia, name = 'eliminar_homilia'),
	url(r'^editar-homilia/(?P<pk>\d+)/$', views.editar_homilia, name = 'editar_homilia'),
	url(r'^editar-guardar-homilia/$', views.editar_guardar_homilia, name = 'editar_guardar_homilia'),
	url(r'^homilia-mes/$', views.homiliasXMes, name = 'homilia_mes'),
	

	url(r'^contacto/$', views.contacto, name = 'contacto'),
	url(r'^enviar-email/$', views.send_email, name = 'send_email'),


	url(r'^publicaciones/$', views.publicaciones, name = 'publicaciones'),
	url(r'^publicacion/(?P<id>\d+)/$', views.publicacion, name = 'publicacion'),
	url(r'^nueva-publicacion/$', views.nueva_publicacion, name = 'nueva_publicacion'),
	url(r'^editar-publicacion/(?P<id>\d+)/$', views.editar_publicacion, name = 'editar_publicacion'),
	url(r'^editar-guardar-publicacion/$', views.editar_guardar_publicacion, name = 'editar_guardar_publicacion'),
	url(r'^eliminar-publicacion/(?P<id>\d+)/$', views.eliminar_publicacion, name = 'eliminar_publicacion'),

	url(r'^login/$', views.log_in, name = 'login'),
	url(r'^logout/$', views.log_out, name = 'logout'),

	url(r'^galeria/$', views.galeria, name = 'galeria'),
	url(r'^galeria/detalle-album/(?P<id>\d+)/$', views.detalle_album, name = 'detalle_album'),
	url(r'^galeria/nuevo-album/$', views.nuevo_album, name = 'nuevo_album'),
	url(r'^galeria/eliminar-album/(?P<id>\d+)/$', views.eliminar_album, name = 'eliminar_album'),
	url(r'^galeria/agregar-imagen/$', views.agregar_imagen, name = 'agregar_imagen'),
	url(r'^galeria/eliminar-imagen/$', views.eliminar_imagen, name = 'eliminar_imagen'),


	url(r'^pastorales-diocesis/$', views.pastoral_diocesis, name = 'pastoral_diocesis'),
	url(r'^pastorales-diocesis/agregar-pastoral/$', views.agregar_pastoral_diocesis, name = 'agregar_pastoral_diocesis'),
	url(r'^pastorales-diocesis/eliminar-pastoral/(?P<id>\d+)/$', views.editar_pastoral_diocesis, name = 'editar_pastoral_diocesis'),
	url(r'^pastorales-diocesis/obtener-pastoral/(?P<id>\d+)/$', views.eliminar_pastoral_diocesis, name = 'eliminar_pastoral_diocesis'),
	url(r'^pastorales-diocesis/editar-pastoral/$', views.pastoral_diocesis_editar_guardar, name = 'pastoral_diocesis_editar_guardar'),

	url(r'^datos-generales/$', views.diocesis_datos, name = 'diocesis_datos'),
	url(r'^datos-generales/obtener-datos/(?P<id>\d+)/$', views.editar_diocesis, name = 'editar_diocesis'),
	url(r'^datos-generales/editar-datos/$', views.editar_guardar_diocesis, name = 'editar_guardar_diocesis'),
]

diocesis/principal/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.template import RequestContext, loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from django.template.defaultfilters import timesince, linebreaks

def index(request):
	listimg = Album.objects.all()
	sacerdote = Empleado.objects.all().count()
	parroquias = Parroquia.objects.all().count()
	pastoral1 = Pastoral.objects.all().count()
	pastoral2 = Pastoral_Diocesi.objects.all().count()
	pt = int(pastoral1) + int(pastoral2)
	if request.user.id:
		empleado = Empleado.objects.get(pk = request.user.id)
		publicacionForm = PublicacionForm(initial={'empleado': empleado})
	else:
		publicacionForm = PublicacionForm()

	for field in publicacionForm.fields:
		publicacionForm.fields[field].widget.attrs['class']='form-control'


	form = AuthenticationForm()
	form.fields['username'].widget.attrs['class'] = 'form-control'
	form.fields['username'].widget.attrs['autofocus'] = 'True'
	form.fields['password'].widget.attrs['class'] = 'form-control'

	publicaciones = Publicacion.objects.all().order_by('-fecha_pub')[:3]

	context = {
		'publicaciones': publicaciones,
		'form': form,
		'publicacionForm': publicacionForm,
		'sc': sacerdote,
		'parroquiasc': parroquias,
		'pastoralesc': pt,
	}
	return render(request, 'index.html', context)


#________________________________Vistas del Administrador del Parroquias___________________________

def parroquia_admin(request):
	empleado=Empleado.objects.filter(estado_obispo= False, estado_sacerdote=True,estado=True)
	lista=[]
	for s in empleado:
		if not Parroquia.objects.filter(empleado=s).exists():
			lista.append(int(s.id))

	form= ParroquiaForm()
	form.fields['empleado'].queryset= Empleado.objects.filter(id__in=lista)
	form.fields['empleado'].label= 'Seleccioné el Sacerdote'
	form.fields['municipio'].label= 'Seleccioné el Municipio'
	form.fields['pastoral'].label= 'Seleccioné las Pastorales'
	form.fields['descripcion'].label= 'Descripción de la Parroquia'

	for field in form.fields:
		form.fields[field].widget.attrs['class']='form-control'
	parroquia= Parroquia.objects.all()
	activo = []
	for e in parroquia:
		if e.estado:
			activo.append('si')
		else:
			activo.append('no')
	data = {
		'parroquia': zip(parroquia, activo),
		'form':form
	}
	return render(request, 'parroquia_admin.html',data )


@login_required()
def parroquia_admin_guardar(request):
	if request.method == 'POST':
		form = ParroquiaForm(data=request.POST,files=request.FILES)

		if form.is_valid():
			p =form.save()

			parroquia='''
				<tr>
					<td>%s</td>
					<td>%s</td>
					<td>%s</td>
					<td><span id="estado-%s">%s</span></td>
					<td>
						<div class="btn-group">
						 	<button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
							</button>
							<ul class="dropdown-menu">
								<a  style="margin-left:30px; "
								    class="btn btn-info" href=""><span class="glyphicon glyphicon-refresh"></span> Actualizar</a>
								<button class="btn btn-danger btn-Aparroquia"
										data-id="%s"
										data-url=""
										style="margin-left:30px; margin-top:5px">Desactivar</button>		
							</ul>
						</div>
					</td>
					<td>%s %s</td>
				</tr>
			'''% (p.nombre,p.telefono,p.direccion,p.id,p.estado,p.id,p.empleado.nombre,p.empleado.apellido)
			return JsonResponse({'response':parroquia})
		else:
			return render(request, 'parroquia_admin.html',{'form': form})


@login_required()
def parroquia_admin_desactivar(request):
	id = request.GET.get('id')
	u = Parroquia.objects.get(pk=id)
	d = Parroquia.objects.filter(pk=id,estado=True)

	if d:
		u.estado= False
		u.save()
		action='Activar'
		valor='False'
	else:
		u.estado= True
		u.save()
		action='Desactivar'
		valor='True'
	return JsonResponse({'action':action,'valor':valor})


@login_required
def parroquia_admin_editar(request, pk):
	p= Parroquia.objects.get(pk=int(pk))
	form = ParroquiaForm(instance=p)
	form.fields['empleado'].label= 'Seleccioné el Sacerdote'
	form.fields['municipio'].label= 'Seleccioné el Municipio'
	form.fields['pastoral'].label= 'Seleccioné las Pastorales'
	form.fields['descripcion'].label= 'Descripción de la Parroquia'
	for field in form.fields:
		form.fields[field].widget.attrs['class']='form-control'

	parroquia= Parroquia.objects.all()
	activo = []
	for e in parroquia:
		if e.estado:
			activo.append('si')
		else:
			activo.append('no')
	
	data ={
		'form':form,
		'pk':pk,
		'abrir':True,
		'parroquia': zip(parroquia, activo)
	}

	return render(request, 'parroquia_admin.html',data )


@login_required
def parroquia_admin_editar_guardar(request):
	pa= Parroquia.objects.get(pk=int(request.POST['id']))
	form = ParroquiaForm(instance=pa, data=request.POST,files=request.FILES)
	if form.is_valid():
		pa= form.save(commit=False)
		pa.save()
		form.save_m2m()

	return HttpResponseRedirect(reverse('principal:parroquia_admin'))



#_____________________________________Vistas de las Parroquias____________________________________

def parroquia(request):
	empleado=Empleado.objects.filter(estado_obispo= False, estado_sacerdote=True,estado=True)
	lista=[]
	for s in empleado:
		if not Parroquia.objects.filter(empleado=s).exists():
			lista.append(int(s.id))

	form= ParroquiaForm()
	form.fields['empleado'].queryset= Empleado.objects.filter(id__in=lista)
	form.fields['empleado'].label= 'Seleccioné el Sacerdote'
	form.fields['municipio'].label= 'Seleccioné el Municipio'
	form.fields['pastoral'].label= 'Seleccioné las Pastorales'
	form.fields['descripcion'].label= 'Descripción de la Parroquia'
	for field in form.fields:
		form.fields[field].widget.attrs['class']='form-control'
	parroquia= Parroquia.objects.filter(estado=True)
	data = {
		'parroquia': parroquia,
		'form':form
	}
	return render(request, 'parroquia.html',data )


@login_required
def parroquia_ver(request,pk):
	parroquia = Parroquia.objects.get(pk=pk)
	data={
		'parroquia':parroquia
	}
	return render(request,'parroquia_ver.html',data)


@login_required()
def parroquia_guardar(request):
	if request.method == 'POST':
		form = ParroquiaForm(request.POST,request.FILES)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('principal:parroquia'))


@login_required
def parroquia_editar(request, pk):
	parroquia= Parroquia.objects.get(pk=int(pk))
	form = ParroquiaForm(instance=parroquia)
	form.fields['empleado'].label= 'Seleccioné el Sacerdote'
	form.fields['municipio'].label= 'Seleccioné el Municipio'
	form.fields['pastoral'].label= 'Seleccioné las Pastorales'
	form.fields['descripcion'].label= 'Descripción de la Parroquia'
	for field in form.fields:
		form.fields[field].widget.attrs['class']='form-control'
	data ={
		'form':form,
		'pk':pk,
		'abrir':True,
		'parroquia':parroquia
	}

	return render(request, 'parroquia_ver.html',data )


@login_required
def parroquia_editar_guardar(request,pk):
	pa= Parroquia.objects.get(pk=int(request.POST['id']))
	form = ParroquiaForm(instance=pa, data=request.POST,files=request.FILES)
	if form.is_valid():
		pa= form.save(commit=False)
		pa.save()
		form.save_m2m()

	return HttpResponseRedirect(reverse('principal:parroquia_ver',args=(pk,)))


@login_required
def parroquia_desactivar(request, pk):
	parroquia = Parroquia.objects.get(pk=pk)
	parroquia.estado=False
	parroquia.save()
	return HttpResponseRedirect(reverse('principal:parroquia'))


#__________________________________________Vistas de las Pastorales_________________________________

def pastoral(request):
	pastoral= Pastoral.objects.all()
	form= PastoralForm()
	for field in form.fields:
		form.fields[field].widget.attrs['class']='form-control'
	form.fields['nombre'].label= 'Seleccioné el Nombre de Pastoral'
	data = {
		'pastoral': pastoral,
		'form':form
	}
	return render(request, 'pastoral.html',data )


@login_required()
def pastoral_guardar(request):
	if request.method == 'POST':
		form = PastoralForm(request.POST,request.FILES)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('principal:pastoral'))


@login_required
def pastoral_editar(request, pk):
	pastoral= Pastoral.objects.all()
	past= Pastoral.objects.get(pk=int(pk))
	form = PastoralForm(instance=past)
	form.fields['nombre'].label= 'Seleccioné el Nombre de Pastoral'
	for field in form.fields:
		form.fields[field].widget.attrs['class']='form-control'
	data ={
		'past':past,
		'form':form,
		'pk':pk,
		'abrir':True,
		'pastoral':pastoral
	}

	return render(request, 'pastoral.html',data )


@login_required
def pastoral_editar_guardar(request):
	past= Pastoral.objects.get(pk=int(request.POST['id']))
	form = PastoralForm(instance=past, data=request.POST,files=request.FILES)
	if form.is_valid():
		past= form.save(commit=False)
		past.save()

	return HttpResponseRedirect(reverse('principal:pastoral'))


@login_required
def pastoral_desactivar(request):
	id = request.GET.get('id')
	p = Pastoral.objects.get(pk=int(id))
	p.delete()
	return JsonResponse({'response':'desactivado'})

#____________________________________________________Vistas del Sacerdote_________________________________

def sacerdote(request):
	parroquia= Parroquia.objects.filter(estado=True)
	data = {
		'parroquia': parroquia
	}
	return render(request, 'sacerdote.html',data )


@login_required
def sacerdote_ver(request,pk):
	empleado = Empleado.objects.get(pk=pk)
	data={
		'empleado':empleado
	}

diocesis/principal/templates/pastorales_diocesis.html
{% extends "base.html" %}

{% block titulo %} Pastorales{% endblock %}

{% block contenido %}
	{% load static %}
	<div id="carousel-1" class="carousel slide" data-ride="carousel">
		<!-- Indicadores -->
		<ol class="carousel-indicators" style="z-index: 1;">
			<li data-target="#carousel-1" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-1" data-slide-to="1"></li>
			<li data-target="#carousel-1" data-slide-to="2"></li>
		</ol>

		<!-- Contenedor de los slide -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img src="{% static 'img/catedral-1.jpg' %}" alt="" class="img-responsive">
				<div class="carousel-caption hidden-xs hidden-sm">
				
				</div>
			</div>
			<div class="item">
				<img src="{% static 'img/fondo2.jpg' %}" alt="" class="img-responsive">
				<div class="carousel-caption hidden-xs hidden-sm">
					
				</div>
			</div>
			<div class="item">
				<img src="{% static 'img/fondo-1.jpg' %}" alt="" class="img-responsive">
				<div class="carousel-caption  hidden-xs hidden-sm">
					
				</div>
			</div>

			<!-- Controles -->
			<a href="#carousel-1" class="left carousel-control" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Anterior</span>
			</a>
			<a href="#carousel-1" class="right carousel-control" role="button" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Siguiente</span>
			</a>
		</div>
	</div><br>
	<div class="container">
		{% if request.user.is_active %}
			<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#formPastoral">Nueva pastoral <span class="glyphicon glyphicon-plus"></span></button><br><br>
		{% endif %}
		<div class="row">

			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="table-responsive">
			   	<table class="table table-bordered hover">
			   		<thead>
			   			<tr>
			   				<th scope="col">Pastoral</th>
			   				{% if request.user.is_staff %}
			   					<th scope="col">Acción</th>
			   				{% endif %}
			   				
			   			</tr>
			   		</thead>
			   		<tbody>
			   			{% for pastoral in pastorales %}
			   				<tr>
				   				<td>{{ pastoral.nombre }}</td>
				   				{% if request.user.is_staff  %}
				   					<td>
					   					<a href="{% url 'principal:editar_pastoral_diocesis' pastoral.id %}" class="btn btn-info" id="bp">Editar <span class="glyphicon glyphicon-pencil"></a>
					   					<a href="#" data-href="{% url 'principal:eliminar_pastoral_diocesis' pastoral.id %}" class="btn btn-danger" data-toggle="modal" data-target="#confirm-delete">Eliminar <span class="glyphicon glyphicon-remove"></span></a>
				   					</td>
				   				{% endif %}
				   				
				   			</tr>
				   		{% empty %}
							<div class="alert alert-danger" role="alert">
								<p>
									No hay Pastorales Disponibles.
								</p>
							</div>
			   			{% endfor %}
			   		</tbody>
			   	</table>
		   </div>
			</div>
		</div>
	</div>
</div>

{# Modal para nueva pastoral #}
	<div class="modal fade" id="formPastoral" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		    <div class="modal-content">
		     	<div class="modal-header">
		        	<h5 class="modal-title" id="exampleModalLabel">Nueva pastoral</h5>
		        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		         		<span aria-hidden="true">&times;</span>
		       		</button>
			        <form action="{% url 'principal:agregar_pastoral_diocesis' %}" method="post" enctype="multipart/form-data">
			        	{% csrf_token %}
			        	<div class="panel-body">
			        		<input type="hidden" value="{{pk}}" name="id">
				        	{{ pastoralForm.as_p }}
				        </div>
				        <div class="panel-footer">
				        	<input type="submit" class="btn btn-success" value="Guardar">
				        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
				        </div>
			        </form>
		    	</div>
		    </div>
		</div>
	</div>
{# Modal para editar pastoral #}
	<div class="modal fade" id="formEditarPastoral" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
		    <div class="modal-content">
		     	<div class="modal-header">
		        	<h5 class="modal-title" id="exampleModalLabel">Editar Homil&iacute;a</h5>
		        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		         		<span aria-hidden="true">&times;</span>
		       		</button>
			        <form action="{% url 'principal:pastoral_diocesis_editar_guardar' %}" method="post" enctype="multipart/form-data">
			        	{% csrf_token %}
			        	<div class="panel-body">
			        		<input type="hidden" value="{{ pk }}" name="id">
				        	{{ editarPastoralForm.as_p }}
				        </div>
				        <div class="panel-footer">
				        	<input type="submit" class="btn btn-success" value="Guardar">
				        	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
				        </div>
			        </form>
		    	</div>
		    </div>
		</div>
	</div>
{# Modal de confirmar eliminacion #}
	<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="myModalLabel">Eliminar Registro</h4>
				</div>
				
				<div class="modal-body">
					¿Desea eliminar este registro?
				</div>
				
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
					<a class="btn btn-danger btn-ok">Eliminar</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block script %}
<script>
	$(function(){
		{% if abrir %}
			$('#formEditarPastoral').modal('show')
		{% endif %}
		
	})
</script>
{% endblock %}

diocesis/principal/templates/sacerdote.html
{% extends "base.html" %}
{% block titulo %}Dirección Sacerdotal{% endblock  %}
{% load static %}

{% block contenido %}
	{% load static %}
	<div class="scontenedor">
		<div class="sacerdotestext">
			<img class="slogo" src="{% static 'img/ds1.png' %}" alt="">
			
		</div>
		<br>
		<div class="container">
			
				<div class="row" >
					{% for p in parroquia  %}
					  <div class="col-sm-6 col-md-4">
					    <div class="thumbnail" id="sacerdote1">
					      <img  class="eee" src="/media/{{p.empleado.imagen}}" alt="...">
					      <div class="caption">
					        <h3 style="color:white;"><strong>Nombre: </strong>{{p.empleado.nombre}} {{p.empleado.apellido}}</h3>
					        <h4 style="color:white;"><strong>Telefono: </strong>{{p.empleado.telefono}}</h4>
					        
					        {% if request.user.is_staff %}
					        	 <p style="color:white;"><a href="{% url 'principal:sacerdote_ver' p.empleado.id %}" 
								   		class="btn btn-warning"  
								   		>Ver Mas <span class="glyphicon glyphicon-eye-open"></span>
									</a>
					        	</p>
					        	<a href="{% url 'principal:parroquia_ver' p.id %}">
					        		 <h3><strong>Parroquia: </strong>{{p.nombre}}</h3>
					        	</a>
					        {% else %}
					        	<h3 style="color:white;"><strong>Parroquia: </strong>{{p.nombre}}</h3>
					        {% endif %}
					        
					      </div>
					    </div>
					  </div>
				  {% empty %}
				</div>
			
				<br>
				<div class="alert alert-danger" role="alert">
					<p>
						No hay Sacerdotes Disponibles.
					</p>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock  %}